export const LOAD_STAFFS = 'LOAD_STAFFS'
export const LOAD_STAFFS_REQUEST = 'LOAD_STAFFS_REQUEST'
export const LOAD_STAFFS_SUCCESS = 'LOAD_STAFFS_SUCCESS'
export const LOAD_STAFFS_FAIL = 'LOAD_STAFFS_FAIL'
